# Generated by Django 6.0.5 on 2026-05-29 02:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=50, verbose_name='OS')),
                ('unidade', models.CharField(blank=True, max_length=100, verbose_name='Unidade')),
                ('dt_coleta', models.DateField(blank=True, null=True, verbose_name='Data de Coleta')),
                ('dt_assinatura', models.DateField(blank=True, null=True, verbose_name='Data de Assinatura')),
                ('procedimento', models.CharField(blank=True, max_length=200, verbose_name='Procedimento')),
                ('microrganismo', models.CharField(blank=True, max_length=200, verbose_name='Microrganismo')),
                ('obs', models.TextField(blank=True, verbose_name='Observações')),
                ('trat_respir', models.TextField(blank=True, verbose_name='Tratamento Respiratório')),
            ],
            options={
                'verbose_name': 'Cultura',
                'verbose_name_plural': 'Culturas',
                'ordering': ['-dt_coleta'],
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=10, unique=True, verbose_name='Sigla')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitais',
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='Antibiograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antibiotico', models.CharField(max_length=150, verbose_name='Antibiótico')),
                ('sensibilidade', models.CharField(choices=[('S', 'Sensível'), ('I', 'Intermediário'), ('R', 'Resistente')], max_length=1, verbose_name='Sensibilidade')),
                ('cultura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antibiograma', to='core.cultura', verbose_name='Cultura')),
            ],
            options={
                'verbose_name': 'Antibiograma',
                'verbose_name_plural': 'Antibiogramas',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('papel', models.CharField(choices=[('consultor', 'Consultor'), ('carregador', 'Carregador')], default='consultor', max_length=20, verbose_name='Papel')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.hospital', verbose_name='Hospital')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Importacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.CharField(max_length=255, verbose_name='Arquivo')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('importado_em', models.DateTimeField(auto_now_add=True, verbose_name='Importado em')),
                ('registros', models.IntegerField(default=0, verbose_name='Registros')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importacoes', to='core.hospital', verbose_name='Hospital')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Importação',
                'verbose_name_plural': 'Importações',
                'ordering': ['-importado_em'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prontuario', models.CharField(max_length=50, verbose_name='Prontuário')),
                ('nome', models.TextField(blank=True, verbose_name='Nome')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='core.hospital', verbose_name='Hospital')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nome'],
                'unique_together': {('hospital', 'prontuario')},
            },
        ),
        migrations.AddField(
            model_name='cultura',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culturas', to='core.paciente', verbose_name='Paciente'),
        ),
        migrations.CreateModel(
            name='Internamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_entrada', models.DateField(verbose_name='Data de Entrada')),
                ('dt_alta', models.DateField(blank=True, null=True, verbose_name='Data de Alta')),
                ('dias', models.IntegerField(default=0, verbose_name='Dias')),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internamentos', to='core.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Internamento',
                'verbose_name_plural': 'Internamentos',
                'ordering': ['dt_entrada'],
                'unique_together': {('paciente', 'dt_entrada')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='cultura',
            unique_together={('paciente', 'os', 'procedimento', 'dt_assinatura')},
        ),
        migrations.CreateModel(
            name='ControleAtbRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acomodacao', models.CharField(blank=True, max_length=100, verbose_name='Acomodação')),
                ('medicamento', models.CharField(max_length=200, verbose_name='Medicamento')),
                ('dt_inicio', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('dias_solic', models.IntegerField(default=0, verbose_name='Dias Solicitados')),
                ('dias_ccih', models.IntegerField(default=0, verbose_name='Dias CCIH')),
                ('dias_em_uso', models.IntegerField(default=0, verbose_name='Dias em Uso')),
                ('medico', models.CharField(blank=True, max_length=150, verbose_name='Médico')),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controle_atb', to='core.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Controle ATB',
                'verbose_name_plural': 'Controles ATB',
                'ordering': ['medicamento', 'dt_inicio'],
                'unique_together': {('paciente', 'medicamento', 'dt_inicio')},
            },
        ),
    ]
