# Generated by Django 6.0.6 on 2026-06-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controleatbraw',
            name='medicamento',
            field=models.CharField(max_length=500, verbose_name='Medicamento'),
        ),
        migrations.AlterField(
            model_name='cultura',
            name='microrganismo',
            field=models.CharField(blank=True, max_length=500, verbose_name='Microrganismo'),
        ),
        migrations.AlterField(
            model_name='cultura',
            name='procedimento',
            field=models.CharField(blank=True, max_length=500, verbose_name='Procedimento'),
        ),
    ]
