# Generated by Django 6.0.6 on 2026-06-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aumenta_max_length_campos_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultura',
            name='microrganismo',
            field=models.TextField(blank=True, verbose_name='Microrganismo'),
        ),
        migrations.AlterField(
            model_name='cultura',
            name='procedimento',
            field=models.TextField(blank=True, verbose_name='Procedimento'),
        ),
    ]
