# Generated by Django 6.0.6 on 2026-06-17 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrar_vinculos(apps, schema_editor):
    """Converte o hospital/papel único de cada usuário em um Vínculo."""
    CustomUser = apps.get_model("core", "CustomUser")
    Vinculo = apps.get_model("core", "Vinculo")
    for user in CustomUser.objects.filter(hospital__isnull=False):
        Vinculo.objects.get_or_create(
            usuario=user,
            hospital_id=user.hospital_id,
            defaults={"papel": user.papel},
        )


def reverter_vinculos(apps, schema_editor):
    """Restaura o primeiro vínculo de cada usuário no campo único."""
    CustomUser = apps.get_model("core", "CustomUser")
    Vinculo = apps.get_model("core", "Vinculo")
    for user in CustomUser.objects.all():
        vinculo = Vinculo.objects.filter(usuario=user).order_by("hospital__sigla").first()
        if vinculo:
            user.hospital_id = vinculo.hospital_id
            user.papel = vinculo.papel
            user.save(update_fields=["hospital", "papel"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_procedimento_microrganismo_textfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('consultor', 'Consultor'), ('carregador', 'Carregador')], default='consultor', max_length=20, verbose_name='Papel')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='core.hospital', verbose_name='Hospital')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Vínculo',
                'verbose_name_plural': 'Vínculos',
                'ordering': ['usuario__username', 'hospital__sigla'],
                'unique_together': {('usuario', 'hospital')},
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='hospitais',
            field=models.ManyToManyField(blank=True, related_name='usuarios', through='core.Vinculo', to='core.hospital', verbose_name='Hospitais'),
        ),
        migrations.RunPython(migrar_vinculos, reverter_vinculos),
        migrations.RemoveField(
            model_name='customuser',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='papel',
        ),
    ]
