# Generated by Django 5.2.17 on 2026-09-14 18:47

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_customuser_hospital_remove_customuser_papel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImagemExame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        upload_to=core.models.imagem_exame_upload_to,
                        verbose_name="Imagem",
                    ),
                ),
                ("dt_exame", models.DateField(verbose_name="Data do Exame")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "enviado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Enviado por",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens_exame",
                        to="core.paciente",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagem de Exame",
                "verbose_name_plural": "Imagens de Exame",
                "ordering": ["-dt_exame", "-criado_em"],
            },
        ),
    ]
